---
- name: testing..
  hosts: myhost
  tasks:
   - name: apt update to install curl
     command: sudo apt-get update
   - name: install curl
     command: sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common
   - name: add deb repo
     become: true
     apt_key:
     url: "https://download.docker.com/linux/ubuntu/gpg"
     state: present
   - name: add repo
     command: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
   - name: update repo
     become: true
     command: apt-get update
   - name: install docker
     command: sudo apt-get -y install docker-c
